#include <calibrae/protocol/get_config.hpp>
#include <calibrae/protocol/config.hpp>
#include <calibrae/protocol/asset.hpp>
#include <calibrae/protocol/types.hpp>
#include <calibrae/protocol/version.hpp>

namespace steemit { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
#else
   result[ "IS_TEST_NET" ] = false;
#endif

   result["SBD_SYMBOL"] = SBD_SYMBOL;
   result["CALIBRAE_100_PERCENT"] = CALIBRAE_100_PERCENT;
   result["CALIBRAE_1_PERCENT"] = CALIBRAE_1_PERCENT;
   result["CALIBRAE_1_TENTH_PERCENT"] = CALIBRAE_1_TENTH_PERCENT;
   result["CALIBRAE_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = CALIBRAE_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["CALIBRAE_ACTIVE_CHALLENGE_COOLDOWN"] = CALIBRAE_ACTIVE_CHALLENGE_COOLDOWN;
   result["CALIBRAE_ACTIVE_CHALLENGE_FEE"] = CALIBRAE_ACTIVE_CHALLENGE_FEE;
   result["CALIBRAE_ADDRESS_PREFIX"] = CALIBRAE_ADDRESS_PREFIX;
   result["CALIBRAE_APR_PERCENT_MULTIPLY_PER_BLOCK"] = CALIBRAE_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["CALIBRAE_APR_PERCENT_MULTIPLY_PER_HOUR"] = CALIBRAE_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["CALIBRAE_APR_PERCENT_MULTIPLY_PER_ROUND"] = CALIBRAE_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["CALIBRAE_APR_PERCENT_SHIFT_PER_BLOCK"] = CALIBRAE_APR_PERCENT_SHIFT_PER_BLOCK;
   result["CALIBRAE_APR_PERCENT_SHIFT_PER_HOUR"] = CALIBRAE_APR_PERCENT_SHIFT_PER_HOUR;
   result["CALIBRAE_APR_PERCENT_SHIFT_PER_ROUND"] = CALIBRAE_APR_PERCENT_SHIFT_PER_ROUND;
   result["CALIBRAE_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = CALIBRAE_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["CALIBRAE_BANDWIDTH_PRECISION"] = CALIBRAE_BANDWIDTH_PRECISION;
   result["CALIBRAE_BLOCKCHAIN_PRECISION"] = CALIBRAE_BLOCKCHAIN_PRECISION;
   result["CALIBRAE_BLOCKCHAIN_PRECISION_DIGITS"] = CALIBRAE_BLOCKCHAIN_PRECISION_DIGITS;
   result["CALIBRAE_BLOCKCHAIN_HARDFORK_VERSION"] = CALIBRAE_BLOCKCHAIN_HARDFORK_VERSION;
   result["CALIBRAE_BLOCKCHAIN_VERSION"] = CALIBRAE_BLOCKCHAIN_VERSION;
   result["CALIBRAE_BLOCK_INTERVAL"] = CALIBRAE_BLOCK_INTERVAL;
   result["CALIBRAE_BLOCKS_PER_DAY"] = CALIBRAE_BLOCKS_PER_DAY;
   result["CALIBRAE_BLOCKS_PER_HOUR"] = CALIBRAE_BLOCKS_PER_HOUR;
   result["CALIBRAE_BLOCKS_PER_YEAR"] = CALIBRAE_BLOCKS_PER_YEAR;
   result["CALIBRAE_CASHOUT_WINDOW_SECONDS"] = CALIBRAE_CASHOUT_WINDOW_SECONDS;
   result["CALIBRAE_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = CALIBRAE_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["CALIBRAE_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = CALIBRAE_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["CALIBRAE_CHAIN_ID"] = CALIBRAE_CHAIN_ID;
   result["CALIBRAE_COMMENT_REWARD_FUND_NAME"] = CALIBRAE_COMMENT_REWARD_FUND_NAME;
   result["CALIBRAE_CONTENT_APR_PERCENT"] = CALIBRAE_CONTENT_APR_PERCENT;
   result["CALIBRAE_CONTENT_CONSTANT_HF0"] = CALIBRAE_CONTENT_CONSTANT_HF0;
   result["CALIBRAE_CONTENT_REWARD_PERCENT"] = CALIBRAE_CONTENT_REWARD_PERCENT;
   result["CALIBRAE_CONVERSION_DELAY"] = CALIBRAE_CONVERSION_DELAY;
   result["CALIBRAE_CONVERSION_DELAY_PRE_HF_16"] = CALIBRAE_CONVERSION_DELAY_PRE_HF_16;
   result["CALIBRAE_CREATE_ACCOUNT_DELEGATION_RATIO"] = CALIBRAE_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["CALIBRAE_CREATE_ACCOUNT_DELEGATION_TIME"] = CALIBRAE_CREATE_ACCOUNT_DELEGATION_TIME;
   result["CALIBRAE_CREATE_ACCOUNT_WITH_STEEM_MODIFIER"] = CALIBRAE_CREATE_ACCOUNT_WITH_STEEM_MODIFIER;
   result["CALIBRAE_CURATE_APR_PERCENT"] = CALIBRAE_CURATE_APR_PERCENT;
   result["CALIBRAE_DEFAULT_SBD_INTEREST_RATE"] = CALIBRAE_DEFAULT_SBD_INTEREST_RATE;
   result["CALIBRAE_EQUIHASH_K"] = CALIBRAE_EQUIHASH_K;
   result["CALIBRAE_EQUIHASH_N"] = CALIBRAE_EQUIHASH_N;
   result["CALIBRAE_FEED_HISTORY_WINDOW"] = CALIBRAE_FEED_HISTORY_WINDOW;
   result["CALIBRAE_FEED_HISTORY_WINDOW_PRE_HF_16"] = CALIBRAE_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["CALIBRAE_FEED_INTERVAL_BLOCKS"] = CALIBRAE_FEED_INTERVAL_BLOCKS;
   result["CALIBRAE_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT"] = CALIBRAE_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT;
   result["CALIBRAE_GENESIS_TIME"] = CALIBRAE_GENESIS_TIME;
   result["CALIBRAE_HARDFORK_REQUIRED_WITNESSES"] = CALIBRAE_HARDFORK_REQUIRED_WITNESSES;
   result["CALIBRAE_INFLATION_NARROWING_PERIOD"] = CALIBRAE_INFLATION_NARROWING_PERIOD;
   result["CALIBRAE_INFLATION_RATE_START_PERCENT"] = CALIBRAE_INFLATION_RATE_START_PERCENT;
   result["CALIBRAE_INFLATION_RATE_STOP_PERCENT"] = CALIBRAE_INFLATION_RATE_STOP_PERCENT;
   result["CALIBRAE_INIT_MINER_NAME"] = CALIBRAE_INIT_MINER_NAME;
   result["CALIBRAE_INIT_PUBLIC_KEY_STR"] = CALIBRAE_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["CALIBRAE_INIT_PRIVATE_KEY"] = CALIBRAE_INIT_PRIVATE_KEY;
#endif
   result["CALIBRAE_INIT_SUPPLY"] = CALIBRAE_INIT_SUPPLY;
   result["CALIBRAE_INIT_TIME"] = CALIBRAE_INIT_TIME;
   result["CALIBRAE_IRREVERSIBLE_THRESHOLD"] = CALIBRAE_IRREVERSIBLE_THRESHOLD;
   result["CALIBRAE_LIQUIDITY_APR_PERCENT"] = CALIBRAE_LIQUIDITY_APR_PERCENT;
   result["CALIBRAE_LIQUIDITY_REWARD_BLOCKS"] = CALIBRAE_LIQUIDITY_REWARD_BLOCKS;
   result["CALIBRAE_LIQUIDITY_REWARD_PERIOD_SEC"] = CALIBRAE_LIQUIDITY_REWARD_PERIOD_SEC;
   result["CALIBRAE_LIQUIDITY_TIMEOUT_SEC"] = CALIBRAE_LIQUIDITY_TIMEOUT_SEC;
   result["CALIBRAE_MAX_ACCOUNT_NAME_LENGTH"] = CALIBRAE_MAX_ACCOUNT_NAME_LENGTH;
   result["CALIBRAE_MAX_ACCOUNT_WITNESS_VOTES"] = CALIBRAE_MAX_ACCOUNT_WITNESS_VOTES;
   result["CALIBRAE_MAX_ASSET_WHITELIST_AUTHORITIES"] = CALIBRAE_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["CALIBRAE_MAX_AUTHORITY_MEMBERSHIP"] = CALIBRAE_MAX_AUTHORITY_MEMBERSHIP;
   result["CALIBRAE_MAX_BLOCK_SIZE"] = CALIBRAE_MAX_BLOCK_SIZE;
   result["CALIBRAE_MAX_CASHOUT_WINDOW_SECONDS"] = CALIBRAE_MAX_CASHOUT_WINDOW_SECONDS;
   result["CALIBRAE_MAX_COMMENT_DEPTH"] = CALIBRAE_MAX_COMMENT_DEPTH;
   result["CALIBRAE_MAX_COMMENT_DEPTH_PRE_HF17"] = CALIBRAE_MAX_COMMENT_DEPTH_PRE_HF17;
   result["CALIBRAE_MAX_FEED_AGE_SECONDS"] = CALIBRAE_MAX_FEED_AGE_SECONDS;
   result["CALIBRAE_MAX_INSTANCE_ID"] = CALIBRAE_MAX_INSTANCE_ID;
   result["CALIBRAE_MAX_MEMO_SIZE"] = CALIBRAE_MAX_MEMO_SIZE;
   result["CALIBRAE_MAX_WITNESSES"] = CALIBRAE_MAX_WITNESSES;
   result["CALIBRAE_MAX_MINER_WITNESSES_HF0"] = CALIBRAE_MAX_MINER_WITNESSES_HF0;
   result["CALIBRAE_MAX_MINER_WITNESSES_HF17"] = CALIBRAE_MAX_MINER_WITNESSES_HF17;
   result["CALIBRAE_MAX_PERMLINK_LENGTH"] = CALIBRAE_MAX_PERMLINK_LENGTH;
   result["CALIBRAE_MAX_PROXY_RECURSION_DEPTH"] = CALIBRAE_MAX_PROXY_RECURSION_DEPTH;
   result["CALIBRAE_MAX_RATION_DECAY_RATE"] = CALIBRAE_MAX_RATION_DECAY_RATE;
   result["CALIBRAE_MAX_RESERVE_RATIO"] = CALIBRAE_MAX_RESERVE_RATIO;
   result["CALIBRAE_MAX_RUNNER_WITNESSES_HF0"] = CALIBRAE_MAX_RUNNER_WITNESSES_HF0;
   result["CALIBRAE_MAX_RUNNER_WITNESSES_HF17"] = CALIBRAE_MAX_RUNNER_WITNESSES_HF17;
   result["CALIBRAE_MAX_SHARE_SUPPLY"] = CALIBRAE_MAX_SHARE_SUPPLY;
   result["CALIBRAE_MAX_SIG_CHECK_DEPTH"] = CALIBRAE_MAX_SIG_CHECK_DEPTH;
   result["CALIBRAE_MAX_TIME_UNTIL_EXPIRATION"] = CALIBRAE_MAX_TIME_UNTIL_EXPIRATION;
   result["CALIBRAE_MAX_TRANSACTION_SIZE"] = CALIBRAE_MAX_TRANSACTION_SIZE;
   result["CALIBRAE_MAX_UNDO_HISTORY"] = CALIBRAE_MAX_UNDO_HISTORY;
   result["CALIBRAE_MAX_URL_LENGTH"] = CALIBRAE_MAX_URL_LENGTH;
   result["CALIBRAE_MAX_VOTE_CHANGES"] = CALIBRAE_MAX_VOTE_CHANGES;
   result["CALIBRAE_MAX_VOTED_WITNESSES_HF0"] = CALIBRAE_MAX_VOTED_WITNESSES_HF0;
   result["CALIBRAE_MAX_VOTED_WITNESSES_HF17"] = CALIBRAE_MAX_VOTED_WITNESSES_HF17;
   result["CALIBRAE_MAX_WITHDRAW_ROUTES"] = CALIBRAE_MAX_WITHDRAW_ROUTES;
   result["CALIBRAE_MAX_WITNESS_URL_LENGTH"] = CALIBRAE_MAX_WITNESS_URL_LENGTH;
   result["CALIBRAE_MIN_ACCOUNT_CREATION_FEE"] = CALIBRAE_MIN_ACCOUNT_CREATION_FEE;
   result["CALIBRAE_MIN_ACCOUNT_NAME_LENGTH"] = CALIBRAE_MIN_ACCOUNT_NAME_LENGTH;
   result["CALIBRAE_MIN_BLOCK_SIZE"] = CALIBRAE_MIN_BLOCK_SIZE;
   result["CALIBRAE_MIN_BLOCK_SIZE_LIMIT"] = CALIBRAE_MIN_BLOCK_SIZE_LIMIT;
   result["CALIBRAE_MIN_CONTENT_REWARD"] = CALIBRAE_MIN_CONTENT_REWARD;
   result["CALIBRAE_MIN_CURATE_REWARD"] = CALIBRAE_MIN_CURATE_REWARD;
   result["CALIBRAE_MIN_PERMLINK_LENGTH"] = CALIBRAE_MIN_PERMLINK_LENGTH;
   result["CALIBRAE_MIN_REPLY_INTERVAL"] = CALIBRAE_MIN_REPLY_INTERVAL;
   result["CALIBRAE_MIN_ROOT_COMMENT_INTERVAL"] = CALIBRAE_MIN_ROOT_COMMENT_INTERVAL;
   result["CALIBRAE_MIN_VOTE_INTERVAL_SEC"] = CALIBRAE_MIN_VOTE_INTERVAL_SEC;
   result["CALIBRAE_MINER_ACCOUNT"] = CALIBRAE_MINER_ACCOUNT;
   result["CALIBRAE_MINER_PAY_PERCENT"] = CALIBRAE_MINER_PAY_PERCENT;
   result["CALIBRAE_MIN_FEEDS"] = CALIBRAE_MIN_FEEDS;
   result["CALIBRAE_MINING_REWARD"] = CALIBRAE_MINING_REWARD;
   result["CALIBRAE_MINING_TIME"] = CALIBRAE_MINING_TIME;
   result["CALIBRAE_MIN_LIQUIDITY_REWARD"] = CALIBRAE_MIN_LIQUIDITY_REWARD;
   result["CALIBRAE_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = CALIBRAE_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["CALIBRAE_MIN_PAYOUT_SBD"] = CALIBRAE_MIN_PAYOUT_SBD;
   result["CALIBRAE_MIN_POW_REWARD"] = CALIBRAE_MIN_POW_REWARD;
   result["CALIBRAE_MIN_PRODUCER_REWARD"] = CALIBRAE_MIN_PRODUCER_REWARD;
   result["CALIBRAE_MIN_RATION"] = CALIBRAE_MIN_RATION;
   result["CALIBRAE_MIN_TRANSACTION_EXPIRATION_LIMIT"] = CALIBRAE_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["CALIBRAE_MIN_TRANSACTION_SIZE_LIMIT"] = CALIBRAE_MIN_TRANSACTION_SIZE_LIMIT;
   result["CALIBRAE_MIN_UNDO_HISTORY"] = CALIBRAE_MIN_UNDO_HISTORY;
   result["CALIBRAE_NULL_ACCOUNT"] = CALIBRAE_NULL_ACCOUNT;
   result["CALIBRAE_NUM_INIT_MINERS"] = CALIBRAE_NUM_INIT_MINERS;
   result["CALIBRAE_ORIGINAL_MIN_ACCOUNT_CREATION_FEE"] = CALIBRAE_ORIGINAL_MIN_ACCOUNT_CREATION_FEE;
   result["CALIBRAE_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = CALIBRAE_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["CALIBRAE_OWNER_AUTH_RECOVERY_PERIOD"] = CALIBRAE_OWNER_AUTH_RECOVERY_PERIOD;
   result["CALIBRAE_OWNER_CHALLENGE_COOLDOWN"] = CALIBRAE_OWNER_CHALLENGE_COOLDOWN;
   result["CALIBRAE_OWNER_CHALLENGE_FEE"] = CALIBRAE_OWNER_CHALLENGE_FEE;
   result["CALIBRAE_OWNER_UPDATE_LIMIT"] = CALIBRAE_OWNER_UPDATE_LIMIT;
   result["CALIBRAE_POST_AVERAGE_WINDOW"] = CALIBRAE_POST_AVERAGE_WINDOW;
   result["CALIBRAE_POST_MAX_BANDWIDTH"] = CALIBRAE_POST_MAX_BANDWIDTH;
   result["CALIBRAE_POST_REWARD_FUND_NAME"] = CALIBRAE_POST_REWARD_FUND_NAME;
   result["CALIBRAE_POST_WEIGHT_CONSTANT"] = CALIBRAE_POST_WEIGHT_CONSTANT;
   result["CALIBRAE_POW_APR_PERCENT"] = CALIBRAE_POW_APR_PERCENT;
   result["CALIBRAE_PRODUCER_APR_PERCENT"] = CALIBRAE_PRODUCER_APR_PERCENT;
   result["CALIBRAE_PROXY_TO_SELF_ACCOUNT"] = CALIBRAE_PROXY_TO_SELF_ACCOUNT;
   result["CALIBRAE_SBD_INTEREST_COMPOUND_INTERVAL_SEC"] = CALIBRAE_SBD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["CALIBRAE_SECONDS_PER_YEAR"] = CALIBRAE_SECONDS_PER_YEAR;
   result["CALIBRAE_RECENT_RSHARES_DECAY_RATE_HF19"] = CALIBRAE_RECENT_RSHARES_DECAY_RATE_HF19;
   result["CALIBRAE_RECENT_RSHARES_DECAY_RATE_HF17"] = CALIBRAE_RECENT_RSHARES_DECAY_RATE_HF17;
   result["CALIBRAE_REVERSE_AUCTION_WINDOW_SECONDS"] = CALIBRAE_REVERSE_AUCTION_WINDOW_SECONDS;
   result["CALIBRAE_ROOT_POST_PARENT"] = CALIBRAE_ROOT_POST_PARENT;
   result["CALIBRAE_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = CALIBRAE_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["CALIBRAE_SAVINGS_WITHDRAW_TIME"] = CALIBRAE_SAVINGS_WITHDRAW_TIME;
   result["CALIBRAE_SBD_START_PERCENT"] = CALIBRAE_SBD_START_PERCENT;
   result["CALIBRAE_SBD_STOP_PERCENT"] = CALIBRAE_SBD_STOP_PERCENT;
   result["CALIBRAE_SECOND_CASHOUT_WINDOW"] = CALIBRAE_SECOND_CASHOUT_WINDOW;
   result["CALIBRAE_SOFT_MAX_COMMENT_DEPTH"] = CALIBRAE_SOFT_MAX_COMMENT_DEPTH;
   result["CALIBRAE_START_MINER_VOTING_BLOCK"] = CALIBRAE_START_MINER_VOTING_BLOCK;
   result["CALIBRAE_START_VESTING_BLOCK"] = CALIBRAE_START_VESTING_BLOCK;
   result["CALIBRAE_SYMBOL"] = CALIBRAE_SYMBOL;
   result["CALIBRAE_TEMP_ACCOUNT"] = CALIBRAE_TEMP_ACCOUNT;
   result["CALIBRAE_UPVOTE_LOCKOUT_HF7"] = CALIBRAE_UPVOTE_LOCKOUT_HF7;
   result["CALIBRAE_UPVOTE_LOCKOUT_HF17"] = CALIBRAE_UPVOTE_LOCKOUT_HF17;
   result["CALIBRAE_VESTING_FUND_PERCENT"] = CALIBRAE_VESTING_FUND_PERCENT;
   result["CALIBRAE_VESTING_WITHDRAW_INTERVALS"] = CALIBRAE_VESTING_WITHDRAW_INTERVALS;
   result["CALIBRAE_VESTING_WITHDRAW_INTERVALS_PRE_HF_16"] = CALIBRAE_VESTING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["CALIBRAE_VESTING_WITHDRAW_INTERVAL_SECONDS"] = CALIBRAE_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["CALIBRAE_VOTE_CHANGE_LOCKOUT_PERIOD"] = CALIBRAE_VOTE_CHANGE_LOCKOUT_PERIOD;
   result["CALIBRAE_VOTE_DUST_THRESHOLD"] = CALIBRAE_VOTE_DUST_THRESHOLD;
   result["CALIBRAE_VOTE_REGENERATION_SECONDS"] = CALIBRAE_VOTE_REGENERATION_SECONDS;
   result["NECTAR_SYMBOL"] = NECTAR_SYMBOL;
   result["STMD_SYMBOL"] = STMD_SYMBOL;
   result["VESTS_SYMBOL"] = VESTS_SYMBOL;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH"] = VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH2"] = VIRTUAL_SCHEDULE_LAP_LENGTH2;

   return result;
}

} } // steemit::protocol
